name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10, 12,14]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.19
    - name: test
      run: go test ./Task
